Table friend {
  id int [pk, increment]
  accepted_on timestamp [note: 'Aceitado Em']
  friend_profile_id int [not null, ref: > profile.id, note: 'Amigo']
  profile_id int [not null, ref: > profile.id, note: 'Pessoa']
  request_on timestamp [not null, note: 'Pedido Em']
  Note: 'Amigo'
}

Table message {
  id int [pk, increment]
  from_profile_id int [not null, ref: > profile.id, note: 'De']
  message text [note: 'Mensagem']
  read_on timestamp [note: 'Lido Em']
  sent_on timestamp [not null, note: 'Enviado Em']
  to_profile_id int [not null, ref: > profile.id, note: 'Para']
  Note: 'Mensagem'
}

Table profile {
  id int [pk, increment]
  avatar text [note: 'Avatar']
  email varchar(250) [unique, note: 'Email']
  name varchar(250) [not null, note: 'Nome']
  profile_user_id int [not null, unique, note: 'Utilizador']
  recovery_key varchar(250) [note: 'Chave de Recuperação']
  recovery_limit timestamp [note: 'Limite de Recuperação']
  Note: 'Perfil'
}

Table people_ws_session {
  id int [pk, increment]
  profile_id int [not null, ref: > profile.id, note: 'Profile']
  session_id varchar(250) [not null, note: 'Sessão ID']
  Note: 'WS Sessão'
}

